name: Test BSD Build

on:
  workflow_dispatch:

jobs:
  build-freebsd:
    runs-on: macos-13  # ← ключ! старый macos с поддержкой xhyve
    steps:
      - uses: actions/checkout@main
      - name: Build on FreeBSD
        uses: cross-platform-actions/action@v0.25.0
        with:
          operating_system: freebsd
          version: "14.2"
          run: |
            sudo pkg install -y gcc make
            make bsd
      - name: Upload
        uses: actions/upload-artifact@main
        with:
          name: freebsd-executable
          path: fresh
